site_name: GenomeSuite Documentation
site_url: https://the-sequencing-center.github.io/genomesuite-docs
use_directory_urls: false

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  logo: assets/tsc-logo.jpg
  favicon: assets/tsc-logo.jpg
  features:
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - toc.follow

copyright:
  Copyright &copy; The Sequencing Center 2024

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - meta
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences

  - toc:
      permalink: true
      toc_depth: 4

plugins:
  - search

extra:
  test: This is a test abbreviation snippet

nav:
  - Home: README.md
  - GenomeSuite Analyzer:
    - Getting started: analyzer-getting-started.md
    - Launch GenomeSuite Analyzer on EC2: analyzer-launch.md
    - Configure the EC2 instance: analyzer-configure-ec2.md
    - Connect to the EC2 instance: analyzer-connect.md
    - Configure AWS credentials: analyzer-configure-aws.md
    - How to get AWS keys: analyzer-how-to-get-aws-keys.md 
    - Run GenomeSuite Analyzer: analyzer-run.md
    - Download the VCF files: analyzer-download-vcf.md
    - Reference genome: analyzer-reference-genome.md
    - License notice: analyzer-license-notice.md
