site_name: GenomeSuite Documentation
site_url: https://the-sequencing-center.github.io/genomesuite-docs
use_directory_urls: false

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  # logo: assets/logo.png
  # favicon: assets/logo.png
  features:
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - toc.follow

copyright:
  Copyright &copy; The Sequencing Center 2024

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - meta
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences

  - toc:
      permalink: true
      toc_depth: 4

plugins:
  - search

extra:
  test: This is a test abbreviation snippet

nav:
  - Home: README.md
  - GenomeSuite Analyzer:
    - Getting Started: getting-started.md
    - Configuring an AWS Account: configure-aws-account.md
